management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}
  instance:
    prefer-ip-address: true
