spring.application.name=payment-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8085

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# Order Service Integration
services.order.url=${ORDER_SERVICE_URL:http://localhost:8084}
services.order.connect-timeout-ms=${ORDER_SERVICE_CONNECT_TIMEOUT_MS:2000}
services.order.read-timeout-ms=${ORDER_SERVICE_READ_TIMEOUT_MS:3000}

resilience.circuit-breaker.failure-rate-threshold=${RESILIENCE_CB_FAILURE_RATE:50}
resilience.circuit-breaker.sliding-window-size=${RESILIENCE_CB_WINDOW_SIZE:10}
resilience.circuit-breaker.minimum-number-of-calls=${RESILIENCE_CB_MIN_CALLS:5}
resilience.circuit-breaker.wait-duration-open-ms=${RESILIENCE_CB_OPEN_MS:10000}
resilience.circuit-breaker.half-open-calls=${RESILIENCE_CB_HALF_OPEN_CALLS:2}
resilience.retry.max-attempts=${RESILIENCE_RETRY_MAX_ATTEMPTS:2}
resilience.retry.wait-duration-ms=${RESILIENCE_RETRY_WAIT_MS:250}
