spring.application.name=payment-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8085

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# Order Service Integration
services.order.url=${ORDER_SERVICE_URL:http://localhost:8084}
services.order.connect-timeout-ms=${ORDER_SERVICE_CONNECT_TIMEOUT_MS:2000}
services.order.read-timeout-ms=${ORDER_SERVICE_READ_TIMEOUT_MS:3000}
