    spring.application.name=order-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8084

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

services.product.url=${PRODUCT_SERVICE_URL:http://localhost:8081}
services.product.connect-timeout-ms=${PRODUCT_SERVICE_CONNECT_TIMEOUT_MS:2000}
services.product.read-timeout-ms=${PRODUCT_SERVICE_READ_TIMEOUT_MS:3000}

services.inventory.url=${INVENTORY_SERVICE_URL:http://localhost:8082}
services.inventory.connect-timeout-ms=${INVENTORY_SERVICE_CONNECT_TIMEOUT_MS:2000}
services.inventory.read-timeout-ms=${INVENTORY_SERVICE_READ_TIMEOUT_MS:3000}